(function(){
var c="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,f="function"==typeof Object.create?Object.create:function(b){function a(){}a.prototype=b;return new a},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var k;a:{var l={m:!0},m={};try{m.__proto__=l;k=m.m;break a}catch(b){}k=!1}g=k?function(b,a){b.__proto__=a;if(b.__proto__!==a)throw new TypeError(b+" is not extensible");return b}:null}var n=g;
function p(){p=function(){};c.Symbol||(c.Symbol=q)}var q=function(){var b=0;return function(a){return"jscomp_symbol_"+(a||"")+b++}}();p();var r=Symbol("Feed");p();var t=Symbol("Feed");function v(b){if(b===t)void 0;else throw"Feed is a _feed_: Cannot construct directly. Use 'Feed.instance'";this.l={}}function w(b){b=b.split(".");try{return b.reduce(function(a,b){return a[b]},v.a)}catch(a){return null}}
function x(b){b=void 0===b?v.a:b;for(var a in b)["t","T","true","TRUE"].includes(b[a])?b[a]=!0:["f","F","false","FALSE"].includes(b[a])&&(b[a]=!1),null!==b[a]&&"object"==typeof b[a]&&x(b[a])}c.Object.defineProperties(v,{b:{configurable:!0,enumerable:!0,get:function(){this[r]||(this[r]=new v(t));return this[r]}},a:{configurable:!0,enumerable:!0,get:function(){return v.b.l},set:function(b){v.b.l=b;x()}}});var y=null;function z(){}
function A(b,a){a={count:a.count,c:a.c,f:a.f};var d;if(location.ancestorOrigins){0==location.ancestorOrigins.length?(a.count=0,a.c=window.location.href):(a.count=1,a.c=window.location.href,a.f=location.ancestorOrigins[location.ancestorOrigins.length-1]);var e=Object.assign({},a)}else{null==b&&(b=window,a.c=window.location.href,a.count=0);try{b.location&&b.location.href&&(d=b.location.href)&&(a.c=d)}catch(u){}try{var h=b.document.referrer;a.count=0}catch(u){a.count++}h&&(a.f=h);b!=top?e=A(b.parent,
a):e=a}void 0;void 0;return e}function C(b){-1<b.indexOf("facebook.com/")&&(b=b.split("?")[0]+"---REDACTED_FOR_PRIVACY---");return b}
c.Object.defineProperties(z,{b:{configurable:!0,enumerable:!0,get:function(){return"Unknown"}},i:{configurable:!0,enumerable:!0,get:function(){y||(y=A(null,{count:0,c:null,f:null}));return y}},f:{configurable:!0,enumerable:!0,get:function(){void 0;try{var b=C(z.i.f.toString())}catch(a){b=z.b}return b}},c:{configurable:!0,enumerable:!0,get:function(){void 0;try{var b=C(z.i.c.toString())}catch(a){b=z.b}return b}},g:{configurable:!0,enumerable:!0,get:function(){if(1<
z.a)var b=z.b;else 1==z.a?b=z.f:0==z.a&&(b=z.c);void 0;return b}},a:{configurable:!0,enumerable:!0,get:function(){var b=-1;try{b=parseInt(z.i.count,10)}catch(a){}return b}}});function D(b){for(var a=[],d=0;d<arguments.length;++d)a[d-0]=arguments[d];a.unshift("ERR : ");console.log.apply(null,a)}function E(b){for(var a=[],d=0;d<arguments.length;++d)a[d-0]=arguments[d];a.unshift("WRN : ");console.log.apply(null,a)};function F(b,a){a=void 0===a?null:a;return new Promise(function(d,e){try{var h=document.createElement("script"),u=!1,B;if(a){var K=function(){window[a]?(void 0,d(null)):u?(B="ScriptUtils::loadScript() timed-out waiting for window['"+a+"'] to be exposed",void 0,e(B)):setTimeout(K,50)};K();setTimeout(function(){u=!0},5E3)}else"object"==typeof h.onload?(h.onload=d,h.onerror=function(){e("ScriptUtils::loadScript() Error loading script : "+
b)}):d(null);h.src=b;document.getElementsByTagName("head")[0].appendChild(h)}catch(na){e("ScriptUtils::loadScript() : Error caught loading "+b)}})};p();Symbol("Tracking");p();var G=Symbol("Tracking");function H(b){if(b!==G)throw"Tracking is a singleton: Cannot construct directly. Use 'Tracking.instance'";}function aa(b,a){a&&b.addEventListener("click",function(){var b=new I("ct");a?window.open(b.a+"&redir="+encodeURIComponent(a)):(new Image).src=b.a;J("ClickThrough");J("ClickThrough")})}function ba(){void 0;if(!w("tm_params.impUrl")){var b=(new I("imp")).a;(new Image).src=b}J("Impression")}
function J(b){var a=w("pixels");a.filter(function(a){return a.trigger.toLowerCase()===b.toLowerCase()}).forEach(function(a){switch(a.type.toLowerCase()){case "javascript":F(a.detail);default:a=a.detail,(new Image).src=a}});v.a.pixels=a.filter(function(a){return a.trigger.toLowerCase()!==b.toLowerCase()})}
function L(b){return new Promise(function(a,d){var e=new Image;e.onload=function(){void 0;a(null)};e.onerror=function(){void 0;d("pixel error : "+b)};e.src=b})}function ca(b){var a=new I("reject");return L(a.a+"&code="+b)}function M(){var b="",a=w("expk"),d=w("sgrpk");a&&(b+="&expk="+a);d&&(b+="&sgrpk="+d);return b}
function da(b){var a={imp:"impression",ct:"clickthrough",vimp:"vimp"};this.b=v.a.statsPixels.filter(function(d){return"stats"==d.type.toLowerCase()&&d.trigger.toLowerCase()==a[b]})[0].detail;this.b+="&burl="+encodeURIComponent(z.c)+"&rurl="+encodeURIComponent(z.f)+"&cpKey="+w("cpKey")+"&mpKey="+w("mpKey")+"&adKey="+w("adKey")+"&astv="+w("astv")+"&apv=20180214-01&s="+w("s");switch(b){case "imp":this.b+="&vw="+document.body.clientWidth.toString()+"&vh="+document.body.clientHeight.toString();break;
case "vimp":this.b+="&w="+w("width")+"&h="+w("height")+"&pw="+w("width")+"&ph="+w("height")+"&vw="+document.body.clientWidth.toString()+"&vh="+document.body.clientHeight.toString();break;case "reject":this.b+="&p1="+z.g+"&p2="+w("cd.fbd.pd")+"&wd="+z.a}this.b+=M()}function I(b){v.a.hasOwnProperty("statsPixels")?this.b=new da(b):this.b=new N(b);this.a=this.b.b}c.Object.defineProperties(I,{a:{configurable:!0,enumerable:!0,get:function(){return(new I("vimp")).a}},b:{configurable:!0,enumerable:!0,get:function(){return(new I("ct")).a}}});
function N(b){var a=this;this.a={};this.g=function(){a.a.sessId=w("session.sessId");a.a.paId=w("paId");a.a.psId=w("psId");a.a.page_url=encodeURIComponent(String(w("page_url")));a.a.burl=encodeURIComponent(String(z.c));a.a.rurl=encodeURIComponent(String(z.f));a.a.did=w("did");a.a.didtype=w("didtype");a.a.expaId=w("expaId");a.a.env=w("env");a.a.conn=w("conn");a.a.moatenabled=w("moatEnabled");a.a.moatfees=w("moatfees");a.a.astv=w("astv");a.a.apv="20180214-01";a.a.rt="HTML5";a.a.vinst="t"};this.o=
function(){a.a.vw=document.body.clientWidth.toString();a.a.vh=document.body.clientHeight.toString();a.a.inc="";a.a.adEngImpQP=w("adEngImpQP")};this.v=function(){a.a.vinst="";a.a.dur="";a.a.inc="";a.a.pw="";a.a.ph="";a.a.adEngViewQP=w("adEngViewQP")};this.i=function(){a.a.bi=w("bi");a.a.adEngClickThruQP=w("adEngClickThruQP")};this.A=function(){a.a.w=w("width");a.a.h=w("height");a.a.vinst="t";a.a.pw=w("width");a.a.ph=w("height");a.a.vw=document.body.clientWidth.toString();a.a.vh=document.body.clientHeight.toString()};
this.s=function(){a.a.bi=w("bi");a.a.price=w("price")};this.u=function(){a.a.p1=z.g;a.a.p2=w("cd.fbd.pd");a.a.msg="Rejected%20Ad";a.a.ssb="true";a.a.wd=z.a};this.g();switch(b){case "imp":this.o();break;case "view":this.v();break;case "ct":this.i();break;case "vimp":this.A();break;case "reject":this.u()}b===w("pt")&&this.s();this.b="https://stats-tm.everesttech.net/stats/1/"+b+this.B+M()}
c.Object.defineProperties(N.prototype,{B:{configurable:!0,enumerable:!0,get:function(){var b="",a="?",d;for(d in this.a)if(0===this.a[d]||this.a[d])b+=a+d+"="+this.a[d],a="&";return b}}});function O(){}function ea(){return new Promise(function(b,a){if(O.a){var d=Object(w("cd.fbd")),e;if((e=z.g)&&e!=z.b){e=P(e);var h=P(d.pd);e=e===h?"":e.endsWith("."+h)||h.endsWith("."+e)?"":"DM"}else e="DI";e?(E("Failed SSB check. Sending rejection pixels and not showing ad"),b=d.aburl.replace("${du}",encodeURIComponent(z.g)).replace("${pd}",d.pd),Promise.all([ca(e),L(b)]).then(a).catch(a)):b(null)}else b(null)})}
function P(b){return b.startsWith("http")?"function"===typeof window.URL?(new URL(b)).hostname:(b=b.match(/:\/\/([^\/$:]+\.[^\/$:]+)/))?b[1]:"NO-TOP-LEVEL-DOMAIN-IN-URL":b.split(/[\/:]/)[0]}c.Object.defineProperties(O,{a:{configurable:!0,enumerable:!0,get:function(){return w("cd.fbd.ssb")}}});p();var Q=Symbol("Viewability");p();var R=Symbol("Viewability");function S(b){if(b!==R)throw"Viewability is a singleton: Cannot construct directly. Use 'Viewability.instance'";}
function fa(){return new Promise(function(b,a){F("https://playtime.tubemogul.com/ace/prod/viewability/ace_viewability-38f3e3.js","AceViewability").then(ha.bind(null,b,a)).catch(function(){H.a(I.a+"&vwbl=err&reason=scriptload");D("Viewability::load : External AceViewability module failed to load");b("Viewability::load : External AceViewability module failed to load")})})}
function ha(b){try{var a={targetElement:S.a.a,video:S.a.b,vimpPixelBase:I.a,viewabilityStandard:"MRC"},d=new window.AceViewability;d.init(a).then(d.start.bind(null)).then(b)}catch(e){H.a(I.a+"&vwbl=err&reason=init"),b("Viewability Unmeasurable")}}c.Object.defineProperties(S,{a:{configurable:!0,enumerable:!0,get:function(){this[Q]||(this[Q]=new S(R));return this[Q]}}});function T(){}
function ia(){var b=["overlay","promoted_video"];S.a.b=!1;S.a.a=document.createElement("div");S.a.a.id="tm_viewability_"+v.a.session.sessId;document.body.appendChild(S.a.a);var a=S.a.a;var d=v.a.adParts[0].assets.find(function(a){return b.includes(a.type)&&!!a.detail});switch(d.mimeType.split("/")[0]){case "text":var e=document.createElement("iframe");e.id="tm_ad_frame_"+v.a.session.sessId;break;case "image":e=document.createElement("img");break;default:return null}e.style.cssText=T.a;a.appendChild(e);
return{j:d,element:e}}
function ja(){var b=ia();if(null===b)return Promise.reject("ERROR in RenderBanner::houseBanner : embedAsset() failed!");if("overlay"===b.j.type)b.element.src=b.j.detail,aa(b.element,b.j.clickURL);else{var a=b.j;b.element.src="https://playtime.tubemogul.com/ace/prod/iframe_bridge/ace_iframe_bridge-f2925c.html?adTag="+encodeURIComponent(a.detail)+"&statsClickURL="+encodeURIComponent(I.b)+"&clickTagOverride="+(a.clickURL?encodeURIComponent(a.clickURL):"")}return Promise.resolve()}
c.Object.defineProperties(T,{a:{configurable:!0,enumerable:!0,get:function(){var b=w("width"),a=w("height");return"width:"+b+"px; height:"+a+"px; margins:0px; border:none; padding:none; overflow:hidden; cursor:pointer;"}}});function ka(){return w("iasMon")?new Promise(function(b){var a="https://pixel.adsafeprotected.com/jload?anId="+w("iasAnId")+"&campId="+w("tmCampaignIdNum")+"&pubId="+w("tmSiteIdNum")+"&placementId="+w("tmPlacementIdNum")+"&chanId="+w("tmFeedIdNum")+"&adsafe_par&bidurl="+w("page_url");F(a).then(b).catch(b)}):Promise.resolve(null)};function la(){return w("moatEnabled")?new Promise(function(b){var a="https://z.moatads.com/tubemogul154237275611/moatad.js#moatClientLevel1="+w("tmCampaignIdNum")+"&moatClientLevel2="+w("tmPlacementIdNum")+"&moatClientLevel3="+w("tmFeedIdNum")+"&moatClientLevel4="+w("tmAdIdNum")+"&moatClientSlicer1="+w("tmSiteIdNum")+"&moatClientSlicer2="+w("page_url");F(a).then(b).catch(b)}):Promise.resolve(null)};function U(){}
function ma(){if(w("bt")){var b=document.body,a=v.a.width,d=v.a.height,e=document.createElement("div");e.id="TM_TRUSTE_GUIDE";e.style.cssText="zIndex:99; position:absolute; left: 0px; top: 0px; width:"+a+"px; height:"+d+"px; pointer-events:none";b.appendChild(e);a=document.createElement("span");a.id="te-clearads-js-efrontier01cont1";a.style.cssText="zIndex";b.appendChild(a);navigator.mimeTypes["application/x-shockwave-flash"]=null;navigator.plugins["Shockwave Flash"]=null;F(U.a)}return Promise.resolve(null)}
c.Object.defineProperties(U,{a:{configurable:!0,enumerable:!0,get:function(){return"https://choices.truste.com/ca?pid=efrontier01&aid=efrontier01&cid=0911ef120x240&c=efrontier01cont1&w="+v.a.width+("&h="+v.a.height)+"&plc=tl&js=10"}}});function V(){return[Object.is,Object.assign,Object.entries,Object.values,Object.getOwnPropertyDescriptors,Array.from,Array.of,Array.prototype.includes,Array.prototype.find,Array.prototype.keys,Array.prototype.findIndex,String.prototype.includes,String.prototype.endsWith,String.prototype.startsWith,window.Promise].reduce(function(b,a){return b&&a},!0)}void 0;function W(b){if(window.ace_using_browser_polyfill)if(V())b();else{var a=setTimeout(function(){clearTimeout(a);clearInterval(d);b()},6E3);var d=setInterval(function(){V()&&(clearInterval(d),b())},50)}else b()};void 0;function X(){W.call(this,function(){void 0;try{v.a=Object.assign({},{tm_params:window.tm_params},window.TM_array[window.tm_auction_id].Feed);x();var b=Promise.resolve(null)}catch(a){b=Promise.reject("DOMFeed::fetch Error")}b.then(ea).then(ba).then(ja).then(fa).then(ka).then(la).then(ma).catch(function(a){D("'bootstrap_display' : Error in bootstrap promise chain: "+a);a.stack&&D(a.stack)})})}X.prototype=f(W.prototype);
X.prototype.constructor=X;if(n)n(X,W);else for(var Y in W)if("prototype"!=Y)if(Object.defineProperties){var Z=Object.getOwnPropertyDescriptor(W,Y);Z&&Object.defineProperty(X,Y,Z)}else X[Y]=W[Y];X.a=W.prototype;new X;
}).call(this)
