$(function(){Usuario.Acessar_Site();Usuario.Load();$("#dialog:ui-dialog").dialog("destroy");$('#slider').cycle({fx:'fade',timeout:4000,delay:4000,next:'#next',prev:'#prev'});$('#produtos').cycle({fx:'scrollRight',timeout:4000,delay:4000,easing:'easeInOutBack'});$('#clientes').cycle({fx:'fade',timeout:4000,delay:4000,});});Config={_Path:function(){return"/";}}
Validacao={Trim:function(str){return str.replace(/^\s+|\s+$/g,"");},IsEmail:function(str){var er=/^[\w-\.]+\@[\w\.-]+\.[a-z]{2,4}$/;return er.test(str.toLowerCase());},IsCPF:function(CPF){var varCPF="";var indSoma,varSoma,varDigito1,varvarDigito2;varCPF=Validacao.fncFiltraValor(CPF);if(varCPF.length!=11)
return(false);if(CPF=="00000000000")
return(false);varSoma=0;for(indSoma=0;indSoma<=8;indSoma++){varSoma=varSoma+(parseInt(varCPF.charAt(indSoma))*(indSoma+ 1));}
varDigito1=varSoma%11;if(varDigito1==10)
varDigito1=0;varSoma=0;for(indSoma=0;indSoma<=7;indSoma++){varSoma=varSoma+(parseInt(varCPF.charAt(indSoma+ 1))*(indSoma+ 1));}
varSoma=varSoma+(varDigito1*9);varDigito2=varSoma%11;if(varDigito2==10){varDigito2=0;}
if(varDigito1==parseInt(varCPF.charAt(9))&&varDigito2==parseInt(varCPF.charAt(10))){return(true);}
return(false);},fncFiltraValor:function(Valor){var s="";var cp="";var invalidos="A&Aacute;&Agrave;&Atilde;&Acirc;&Auml;BC&Ccedil;DE&Eacute;&Egrave;&Ecirc;&Euml;FGHI&Iacute;&Igrave;&Icirc;&Iuml;JKLMNO&Oacute;&Ograve;&Otilde;&Ocirc;&Ouml;PQRSTU&Uacute;&Ugrave;&Ucirc;&Uuml;VWXYZa&aacute;&agrave;&atilde;&acirc;&auml;bc&ccedil;de&eacute;&egrave;&ecirc;&euml;fghi&iacute;&igrave;&icirc;&iuml;jklmno&oacute;&ograve;&otilde;&ocirc;&ouml;pqrstu&uacute;&ugrave;&ucirc;&uuml;vwxyz`&acute;^~&uml;'\"@#$%&uml;&*()-_+={}[]<>:;?,./|";vr=Valor;tam=vr.length;for(i=0;i<tam;i++){if(invalidos.indexOf(vr.substring(i,i+ 1))==-1){s=s+ vr.substring(i,i+ 1);}}
return s}}
Page={DisplayIn:function(obj,str){if(obj.value==str){obj.value="";}},DisplayOut:function(obj,str){if(obj.value==""){obj.value=str;}},DisplayValidate:function(objId,str,msg){var obj=document.getElementById(objId);if((obj.value==str)||(obj.value=="")||(obj.value==null)){alert(msg);obj.focus();return false;}
return true;},Display:function(seletor,chave_default){$(seletor).val(chave_default);$(seletor).focus(function(){if($(this).val()==chave_default){$(this).val("");}});$(seletor).blur(function(){if($(this).val()==""){$(this).val(chave_default);}});},OpenUrlSelect:function(Obj){var value=Obj.options[Obj.selectedIndex].value;var array=value.split(";");window.open(array[1],array[0]);},Favorito:function(url,title){if(window.sidebar){window.sidebar.addPanel(title,url,"");}else
if(window.opera&&window.print){var mbm=document.createElement('a');mbm.setAttribute('rel','sidebar');mbm.setAttribute('href',url);mbm.setAttribute('title',title);mbm.click();}else
if(document.all){window.external.AddFavorite(url,title);}}}
Usuario={Acessar_Site:function(){var day=new Date();var id='acesso_site_'+ day.getFullYear()+""+ day.getMonth()+""+ day.getDate()+""+ day.getHours();var acesso=$.cookie(id);if(acesso!="OK"){$.post(Config._Path()+"ajax.php",{"function":"Acessar_Site","session":id},function(rs){$.cookie(id,"OK",{expires:1});},"json");}
$.post(Config._Path()+"ajax.php",{"function":"Atualizar_Online","session":id},function(rs){},"json");},Acessar_Noticia:function(IdNoticia){var day=new Date();var id='acesso_noticia_'+ IdNoticia+'_'+ day.getFullYear()+""+ day.getMonth()+""+ day.getDate()+""+ day.getHours();var acesso=$.cookie(id);if(acesso!="OK"){$.post(Config._Path()+"ajax.php",{"function":"Acessar_Noticia","session":id,"IdNoticia":IdNoticia},function(rs){$.cookie(id,"OK",{expires:1});},"json");}},Load:function(){},Aviso:function(msg){if(msg.length>0){msg='<p><b>Atenção:</b></p>'+ msg;$("#dialog-message").attr("title","Aviso");$("#dialog-message").html(msg);$("#dialog-message").dialog({modal:true,buttons:{Ok:function(){$(this).dialog("close");}}});}}}
Enquete={tagIdForm:"",tagNameAlternativa:"",tagIdBtn:"",tagIdLoader:"",IdEnquete:"",Load:function(tagIdForm,tagNameAlternativa,tagIdBtn,tagIdLoader,IdEnquete){Enquete.tagIdForm=tagIdForm;Enquete.tagNameAlternativa=tagNameAlternativa;Enquete.tagIdBtn=tagIdBtn;Enquete.tagIdLoader=tagIdLoader;Enquete.IdEnquete=IdEnquete;$(Enquete.tagIdForm).submit(function(){return Enquete.Votar();});},Votar:function(){var msg="";var IdAlternativa=$("input[name='"+ Enquete.tagNameAlternativa+"']:checked").val()||"";if(IdAlternativa.length<=0){msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>Selecione uma alternativa da enquete</p>';}
if(msg.length<=0){var carregando=$(Enquete.tagIdLoader);var btSubmit=$(Enquete.tagIdBtn);carregando.show();btSubmit.attr('disabled','disabled');$.post(Config._Path()+"ajax.php",{"function":"Enquete_Votar","IdEnquete":Enquete.IdEnquete,"IdAlternativa":IdAlternativa},function(rs){switch(rs["status"]){case 0:{msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>'+ rs["aviso"]+';</p>';}
break;case 1:{msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>'+ rs["aviso"]+';</p>';}
break;}
Enquete.Aviso(msg);carregando.hide();btSubmit.removeAttr('disabled');},"json");}
Enquete.Aviso(msg);return false;},Aviso:function(msg){if(msg.length>0){msg='<p><b>Atenção:</b></p>'+ msg;$("#dialog-message").attr("title","Aviso");$("#dialog-message").html(msg);$("#dialog-message").dialog({modal:true,width:400,buttons:{Ok:function(){$(this).dialog("close");}}});}}}
Newsletter={Load:function(){$("#FrmNewsletter").submit(function(){return Newsletter.Submit();});},Submit:function(){var FrmNewsletterEmail=Validacao.Trim($("#FrmNewsletterEmail").val());var btSubmit=$("#FrmNewsletterAdd");var msg="";if(!Validacao.IsEmail(FrmNewsletterEmail)){msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span><b>E-mail inválido</b>, preencha corretamente;</p>';}
if(msg.length<=0){var carregando=$("#newsletterCarregando");carregando.show();btSubmit.attr('disabled','disabled');$.post(Config._Path()+"ajax.php",{"function":"Newsletter","Email":FrmNewsletterEmail},function(rs){switch(rs["status"]){case 0:{msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>'+ rs["aviso"]+';</p>';}
break;case 1:{msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>'+ rs["aviso"]+';</p>';document.forms.FrmNewsletter.reset();}
break;}
Newsletter.Aviso(msg);carregando.hide();btSubmit.removeAttr('disabled');},"json");}
Newsletter.Aviso(msg);return false;},Aviso:function(msg){if(msg.length>0){msg='<p><b>Atenção:</b></p>'+ msg;$("#dialog-message").attr("title","Aviso");$("#dialog-message").html(msg);$("#dialog-message").dialog({modal:true,width:400,buttons:{Ok:function(){$(this).dialog("close");}}});}}}
IMC={Load:function(){$("#IMCform").submit(function(){IMC.Calcular();return false;});},Calcular:function(){var peso=parseInt($("#IMCpeso").val()||0);var altura=parseInt($("#IMCaltura").val()||0);var btSubmit=$("#IMCbtn");var msg="";if(peso<=0){msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>Preencha campo <b>Peso</b> em KG (ex: 70);</p>';}
if(altura<=0){msg+='<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 10px 0;"></span>Preencha campo <b>Altura</b> em CM (ex: 170);</p>';}
if(msg.length<=0){altura=altura/100;var imc=peso/(altura*altura);imc=IMC.custRound(imc,1);var legenda="";if(imc<18.5)
legenda="Peso Baixo";if(imc>=18.5&&imc<=24.9)
legenda="Peso Ideal";if(imc>=25&&imc<=29.9)
legenda="Acima do Peso";if(imc>=30&&imc<=34.9)
legenda="Obesidade Tipo I";if(imc>=35&&imc<=39.9)
legenda="Obesidade Tipo II";if(imc>=40&&imc<=49.9)
legenda="Obesidade Mórbida";if(imc>40)
legenda="Obesidade Extrema";msg="Você está com IMC <b>"+imc+"</b> que é <b>"+legenda+"</b>";}
IMC.Aviso(msg);return false;},custRound:function(x,places){return(Math.round(x*Math.pow(10,places)))/Math.pow(10,places)
},Aviso:function(msg){if(msg.length>0){msg='<p><b>Atenção:</b></p>'+ msg;$("#dialog-message").attr("title","Aviso");$("#dialog-message").html(msg);$("#dialog-message").dialog({modal:true,width:400,buttons:{Ok:function(){$(this).dialog("close");}}});}}}
$.datepicker.regional['pt-BR']={yearRange:"-80:+0",changeYear:false,showButtonPanel:true,dateFormat:'dd/mm/yy',minDate:new Date(),dayNames:['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],dayNamesMin:['D','S','T','Q','Q','S','S','D'],dayNamesShort:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],monthNames:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],monthNamesShort:['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],nextText:'Próximo',prevText:'Anterior',currentText:'Hoje',closeText:'X'};$.datepicker.setDefaults($.datepicker.regional['pt-BR']);$(function(){$(".calendario").datepicker();});var keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZ"+"abcdefghijklmnopqrstuvwxyz"+"0123456789+/=";function encode64(inp)
{var out="";var chr1,chr2,chr3="";var enc1,enc2,enc3,enc4="";var i=0;do{chr1=inp.charCodeAt(i++);chr2=inp.charCodeAt(i++);chr3=inp.charCodeAt(i++);enc1=chr1>>2;enc2=((chr1&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else if(isNaN(chr3)){enc4=64;}
out=out+ keyStr.charAt(enc1)+ keyStr.charAt(enc2)+ keyStr.charAt(enc3)+
keyStr.charAt(enc4);chr1=chr2=chr3="";enc1=enc2=enc3=enc4="";}while(i<inp.length);return out;}
function decode64(inp)
{var out="";var chr1,chr2,chr3="";var enc1,enc2,enc3,enc4="";var i=0;var base64test=/[^A-Za-z0-9\+\/\=]/g;if(base64test.exec(inp)){alert("There were invalid base64 characters in the input text.\n"+"Valid base64 characters are A-Z, a-z, 0-9, ?+?, ?/?, and ?=?\n"+"Expect errors in decoding.");}
inp=inp.replace(/[^A-Za-z0-9\+\/\=]/g,"");do{enc1=keyStr.indexOf(inp.charAt(i++));enc2=keyStr.indexOf(inp.charAt(i++));enc3=keyStr.indexOf(inp.charAt(i++));enc4=keyStr.indexOf(inp.charAt(i++));chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;out=out+ String.fromCharCode(chr1);if(enc3!=64){out=out+ String.fromCharCode(chr2);}
if(enc4!=64){out=out+ String.fromCharCode(chr3);}
chr1=chr2=chr3="";enc1=enc2=enc3=enc4="";}while(i<inp.length);return out;}